id: P009118
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ294450
  title: 'ཀློང་སྙིང་ཇོ་ལུགས་སྒྲོལ་དཀར་གྱི་སྐོར་ཆོག་བསྒྲིགས།

    '
  author: ''
  volumes:
    d52bc3a38f0a4c7aa438b4e160ed2922:
      image_group_id: I4CZ294573
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
