id: IE414CDDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T05:02:13+00:00'
last_modified: '2022-06-08T08:45:01.634671+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294450
  title: 'ཀློང་སྙིང་ཇོ་ལུགས་སྒྲོལ་དཀར་གྱི་སྐོར་ཆོག་བསྒྲིགས།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C6BA:
      image_group_id: I4CZ294573
      title: ''
      total_pages: 210
      order: 1
      base_file: C6BA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
